apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: php-app-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/SEU_USUARIO/k8s.git'  # Substitua pelo seu repositório
    path: .
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: php-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
