apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-app
  namespace: php-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: php-app
  template:
    metadata:
      labels:
        app: php-app
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
          name: http
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: nginx.conf
        - name: app-files
          mountPath: /var/www/html
      - name: php-app
        image: php:8.2-fpm-alpine
        volumeMounts:
        - name: app-files
          mountPath: /var/www/html
        - name: php-app-config
          mountPath: /usr/local/etc/php/conf.d/custom.ini
          subPath: custom.ini
        livenessProbe:
          httpGet:
            path: /health-check.php
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health-check.php
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: php-app-config
        configMap:
          name: php-app-config
      - name: nginx-config
        configMap:
          name: nginx-config
      - name: app-files
        configMap:
          name: php-files
          defaultMode: 0644
---
apiVersion: v1
kind: Service
metadata:
  name: php-app-service
  namespace: php-app
spec:
  selector:
    app: php-app
  ports:
  - name: http
    port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: php-app-ingress
  namespace: php-app
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "32k"
spec:
  rules:
  - host: plataforma.devalt.com.br
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: varnish-service
            port:
              number: 80